version: '3.8'

services:
  interview-service:
    build: .
    ports:
      - "8005:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/interview_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview_db
    ports:
      - "5437:5432"
    volumes:
      - interview_postgres_data:/var/lib/postgresql/data

volumes:
  interview_postgres_data:
